name: Python Package using Conda

on:
  push:
    paths:
    - 'speechtotext/**'
    - '*.py'
    - '*.yml'
    - 'docs/source/**'
    - '.github/**'

  pull_request:
    paths: 
    - 'speechtotext/**'
    - '*.py'
    - '*.yml'
    - 'docs/source/**'


jobs:

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file environment_build.yml --name base

    - name: Build documentation html
      run: |
        cd docs;make html;cd ..
    
    - name: Build documentation markdown
      run: |
        cd docs;make markdown;cd ..
    - name: Commit and push documentation 
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A -f docs/build/**
        timestamp=$(date -u)
        git commit -m "Created documentation from github actions: ${timestamp}" || exit 0
        git push

  update-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-linux
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: 'docs/build/html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
